### ISSUE TITLE
Getting error_description_invalid_argument when attempting to share from iOS

### ISSUE THREAD

**Issue by summera** [Snapchat/creative-kit-sample#22]
I keep getting the following error from `#startSending`:

> Error Domain=SCSDKCreativeKitErrorDomain Code=1 "error_description_invalid_argument" UserInfo={NSLocalizedRecoverySuggestion=Please check documentation for potential mistakes. Please content snapkit-support@snap.com if problem persists., NSLocalizedDescription=error_description_invalid_argument, NSLocalizedFailureReason=}

I am downloading a video locally on the device and retrieving the URL of the `PHAsset` using `PHImageManager.default().requestAVAsset`. I'm then using that url to create a `SCSDKSnapVideo` that I'm then attempting to send to Snapchat. Essentially something like:

```swift
PHImageManager.default().requestAVAsset(forVideo: self, options: options, resultHandler: {(asset: AVAsset?, audioMix: AVAudioMix?, info: [AnyHashable : Any]?) -> Void in
    if let urlAsset = asset as? AVURLAsset {
        let localVideoUrl: URL = urlAsset.url as URL
        let video = SCSDKSnapVideo(videoUrl: localVideoUrl)
        content = SCSDKVideoSnapContent(snapVideo: video)
        self.snapApi.startSending(content) { [weak self] (error: Error?) in
        }
    } else {
        
    }
})
```

What am I missing here?

**Comment by NishidaRyu416** [comment]
I am also facing the error: I tried downloading a video to the cache, document, and temporary directories but I could not get it worked.
By the way, sharing a video selected from the camera roll works fine.

**Comment by summera** [comment]
@eberglundsc @tphillipssc @davidxiasc @bkirbysc sorry to ping you directly, but any chance we could get some assistance with this issue?

**Comment by shine93** [comment]
how to resovle this？

**Comment by driefler** [comment]
@summera, can you verify the following:
- the video type is MOV or MP4
- Video is shorter than 60 seconds
- Video is smaller than 100MB

**Comment by summera** [comment]
@driefler thanks for the response.

> @summera, can you verify the following:
> 
> * the video type is MOV or MP4

Yes, the video is an `MP4` file.

> * Video is shorter than 60 seconds

Yes.

> * Video is smaller than 100MB

Yes.

Here's an example video that I've tried.

[small.mp4.zip](https://github.com/Snapchat/creative-kit-sample/files/5071995/small.mp4.zip)

**Comment by summera** [comment]
@driefler any ideas? Thanks for your help.

**Comment by bkirbysc** [comment]
Hi, we are working on an update that should fix this

**Comment by xincc** [comment]
I catch the same error, any solution? @driefler

**Comment by shine93** [comment]
> how to resovle this？

I solve it by:
1. pod 'SnapSDK', '1.4.0', :subspecs => ['SCSDKCreativeKit'].         The latest version can not work, '1.4.0' can.
2. check snapchat logged in a demo user if using develop environment.
3. Do not use assetURL.  Download a video and save it to document directory, use this path.

**Comment by NishidaRyu416** [comment]
@shine93 
Thanks for sharing your tips!
Can the directory we download a video to can be other than the document directory such as cache or temp?

**Comment by shine93** [comment]
I think can.  It's no difference, you can try.

**Comment by NishidaRyu416** [comment]
That's right! Sorry for being lazy: I am using this from React Native so I was reluctant to compile objective-c over and over again:( 
I'll let you know whether it works!

**Comment by NishidaRyu416** [comment]
> Hi, we are working on an update that should fix this

I realised you updated the SDK, does the version 1.6.4 fixe this issue?

**Comment by bkirbysc** [comment]
Hi, yes 1.6.4 adds support for ISO-based MP4 sharing

**Comment by shine93** [comment]
> Hi, yes 1.6.4 adds support for ISO-based MP4 sharing

I just pod search, don't see 1.6.4.  why???

-> SnapSDK (1.6.3)
   Snap Kit lets developers like you integrate some of Snapchat’s best features
   across your platform.
   pod 'SnapSDK', '~> 1.6.3'
   - Homepage: https://kit.snapchat.com
   - Source:
   https://storage.googleapis.com/snap-kit-build/scsdk/ios/release/latest/SCSDK-1.6.3.tar.gz
   - Versions: 1.6.3, 1.6.2, 1.6.1, 1.6.0, 1.5.0, 1.4.4, 1.4.3, 1.4.2, 1.4.1,
   1.4.0, 1.3.5, 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.2.2, 1.2.1, 1.2.0, 1.1.5,
   1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.0
   [cocoapods repo]
   - Subspecs:
     - SnapSDK/SCSDKCreativeKit (1.6.3)
     - SnapSDK/SCSDKLoginKit (1.6.3)
     - SnapSDK/SCSDKBitmojiKit (1.6.3)
     - SnapSDK/SCSDKStoryKit (1.6.3)

**Comment by bkirbysc** [comment]
You may need to run `pod repo update`

**Comment by NishidaRyu416** [comment]
Thanks! I could confirm that it’s working fine now even on iOS with React Native!

**Comment by bkirbysc** [comment]
Great, thank you for confirming!

**Comment by nicollasmatheus** [comment]
seems that latest sdk 1.6.4 is breaking ios buils with React Native. any thoughts why?

**Comment by franzejr** [comment]
I'm also having troubles with the latest version 1.6.4 when sharing from iOS.
