### ISSUE TITLE
Demo failed to pull snapchat app

### ISSUE THREAD

**Issue by YJExpand** [Snapchat/creative-kit-sample#25]
I have replaced the scsdkclientid in info with my test environment ID, but failed to pull up the app to share. At present, my account has opened loginkit and passed the audit. Later, I turned on the switch of creativekit, but it was not approved. I want to test the function of creativekit first, but I can't pull up snapchat app. Do you have to submit an application to test the function of creativekit?

**Comment by YJExpand** [comment]
Application is IOS

**Comment by YJExpand** [comment]
I have found the reason. I have wrong configuration of whitelist

**Comment by mercnmore** [comment]
> I have found the reason. I have wrong configuration of whitelist

I am having the same issue. Can you please help me understand what was configured wrong on your end ?
