### ISSUE TITLE
Error when calling SCSDKSnapAPI.startSending()

### ISSUE THREAD

**Issue by zach-fuller** [Snapchat/creative-kit-sample#6]
I'm trying to integrate Creative Kit into my app but am getting the following error when trying to send the sticker to Snapchat: "error_description_encryption_metadata_read_failure"

I've tried to find a solution but can't seem to get it to work, any help would be greatly appreciated. Here is the code I am using:
```
class ViewController: UIViewController {
    
    var snapAPI: SCSDKSnapAPI?
    
    override func loadView() {
        view = contentView
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        snapAPI = SCSDKSnapAPI()
    }
    
    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        sendStickerToSnapchat()
    }
    
    func sendStickerToSnapchat() {
        let renderer = UIGraphicsImageRenderer(size: contentView.pollCard.bounds.size)
        let image = renderer.image { ctx in
            view.drawHierarchy(in: contentView.pollCard.bounds, afterScreenUpdates: true)
        }
        
        let sticker = SCSDKSnapSticker(stickerImage: image)
        let snap = SCSDKNoSnapContent()
        snap.sticker = sticker
        
        snapAPI?.startSending(snap, completionHandler: { (error) in
            guard error == nil else {
                print("Error is", error)
                return
            }
        })
    }
    
}
```

**Comment by maxbbb** [comment]
For anyone looking at this later, I fixed this error by making sure the bundle ids matched up in the snap developer portal and my build settings.

**Comment by joshwolff1** [comment]
Expanding on this - you must (1) set up your app in the developer portal and (2) make sure you are logged into a demo user account in the Snapchat app

**Comment by ilkerc** [comment]
Checked bundle ids and demo user names, after hours of struggling discovered that production and development bundle identifiers had to be different. I think the kit portal should at least warn about that -not that I agree about distinct bundle identifiers-

**Comment by dbezrukov** [comment]
Hi there,
Is it really true that we need to have different bundle ids for dev and production stages of the **same** application? 
How to approach this?
