### ISSUE TITLE
Unable to swipe up to open link -- Creative Kit

### ISSUE THREAD

**Issue by dondy1996** [Snapchat/creative-kit-sample#72]
This is working on saved Snaps as of December 2022, but when I add new Snaps, there is not an option swipe up anymore to view the link anymore. I can click the 3 dot icon and I'll see the link there. I'm using the same snippet I've always had: `snap.attachmentUrl = "https://google.com"`
![IMG_CE7B561EBD29-1](https://user-images.githubusercontent.com/35268964/213595454-58b02600-1040-4b8a-b28b-e8579ec567d3.jpeg)

**Comment by duncanday96** [comment]
this is on staging btw
